apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotfiles-workspace
  labels:
    app.kubernetes.io/name: dotfiles-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
