apiVersion: v1
kind: Secret
metadata:
  name: ${GITHUB_APP_SECRET_NAME}
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  private-key.pem: |
    -----BEGIN PRIVATE KEY-----
    replace-with-github-app-private-key
    -----END PRIVATE KEY-----
